from pathlib import Path

root = Path(__file__).resolve().parents[1]
js_path = root / 'data' / 'extra-columns.js'
text = js_path.read_text(encoding='utf-8')

rich_ch35 = r'''
  function richCh35Html() {
    return '' +
      '<div class="ch35-mobile-nav"><a href="#生活系统">生活系统</a><a href="#秩序系统">秩序系统</a><a href="#兴趣半径">兴趣半径</a><a href="#审美升级">审美升级</a><a href="#场景展示">场景展示</a><a href="#30天计划">30天计划</a></div>' +
      '<article class="ch35-article">' +
      '<section class="ch35-hero"><div class="ch35-hero__content"><span class="ch35-kicker">CH35 · 30天生活方式建设手册</span><h2>男性生活方式建设：让吸引力长在真实生活里</h2><p>长期吸引力不是靠几句漂亮话制造出来的，而是从你的房间、作息、身体状态、衣着气味、兴趣结构、社交半径和独处质量里自然透出来。真正有后劲的人，不是看起来很会撩，而是生活本身就值得靠近。</p><div class="ch35-hero__tags"><span>基础秩序</span><span>身体精力</span><span>居住审美</span><span>兴趣半径</span><span>真实展示</span></div></div><div class="ch35-hero__card"><strong>核心判断</strong><span>你能不能把一个普通周末过得干净、有内容、有恢复感，决定了关系进入日常后是否还有吸引力。</span></div></section>' +
      '<div class="ch35-dashboard"><div><b>5层</b><span>生活方式底盘</span></div><div><b>8项</b><span>可执行升级模块</span></div><div><b>12个</b><span>高频展示场景</span></div><div><b>30天</b><span>低成本训练计划</span></div></div>' +
      '<section id="生活系统" class="ch35-section"><div class="ch35-section-banner"><span>01</span><div><h2>一、生活系统：吸引力不是表演，是日常稳定输出</h2><p>很多人把生活方式误解成昂贵消费、网红打卡和精修照片。真正有效的生活方式，是别人靠近你以后发现：这个人有秩序、有审美、有能量，也有自己的世界。</p></div></div><div class="ch35-system-grid"><div class="ch35-system-card"><span>底层</span><h3>干净与秩序</h3><p>房间、衣物、气味、桌面、手机相册和时间安排，先让生活不失控。</p></div><div class="ch35-system-card"><span>第二层</span><h3>身体与精力</h3><p>睡眠、运动、体态、饮食，让你不是靠硬撑社交，而是真的有精神。</p></div><div class="ch35-system-card"><span>第三层</span><h3>审美与表达</h3><p>穿搭、空间、照片、语言风格，传递干净、稳定、舒服的个人气质。</p></div><div class="ch35-system-card"><span>第四层</span><h3>兴趣与内容</h3><p>运动、阅读、城市探索、手作、摄影、音乐、烹饪，让你有可分享的体验。</p></div><div class="ch35-system-card"><span>第五层</span><h3>关系与口碑</h3><p>朋友局里的靠谱、对服务人员的礼貌、对女性的尊重，组成长期可信度。</p></div></div><div class="ch35-summary"><strong>一句话原则：</strong>生活方式建设不是装成人设，而是把自己过成一个更稳定、更舒展、更有选择的人。</div></section>' +
      '<section id="秩序系统" class="ch35-section"><div class="ch35-section-banner"><span>02</span><div><h2>二、秩序系统：先把低分项清掉</h2><p>吸引力提升最先见效的，不是买贵东西，而是把明显扣分的混乱感降下来。干净、规律、守时、清爽，是所有风格的底色。</p></div></div><div class="ch35-card-grid"><div class="ch35-card"><h3>空间秩序</h3><p>床铺每天复位，地面无杂物，桌面只保留正在使用的物品。女生到访前临时收拾不够，真正的稳定来自平时就干净。</p><ul><li>每周一次深度清洁。</li><li>入口、卫生间、床边是重点区域。</li><li>准备干净拖鞋、纸巾、垃圾袋和基础饮品。</li></ul></div><div class="ch35-card"><h3>衣物秩序</h3><p>衣服不必多，但要合身、干净、无异味、无明显褶皱。把不能穿出门的旧衣服及时淘汰。</p><ul><li>建立白T、衬衫、针织、牛仔裤、休闲鞋基础组合。</li><li>内衣袜子定期更新。</li><li>出门前检查领口、鞋面、头发和指甲。</li></ul></div><div class="ch35-card"><h3>时间秩序</h3><p>约会迟到、临时改计划、长期熬夜，会让人觉得你生活不可托付。稳定的人不一定忙少，而是能管理承诺。</p><ul><li>邀约前确认交通和备选方案。</li><li>工作日固定睡前收尾仪式。</li><li>重要约会提前15分钟到附近。</li></ul></div><div class="ch35-card"><h3>数字秩序</h3><p>朋友圈、头像、签名、相册和聊天习惯也在传递生活状态。少一点抱怨、炫耀和低俗内容，多一点真实记录。</p><ul><li>清理负能量转发和过度自拍。</li><li>保留3到6张真实生活照片。</li><li>不要把暧昧截图和隐私当谈资。</li></ul></div></div></section>' +
      '<section class="ch35-section"><div class="ch35-section-banner"><span>03</span><div><h2>三、错误人设 vs 成熟建设：别把生活方式做成包装工程</h2><p>生活质感不是让别人以为你很厉害，而是让别人和你相处时更放松、更安心、更有期待。</p></div></div><div class="ch35-compare"><div class="ch35-box-wrong"><h3>错误做法</h3><ul><li>房间混乱、作息崩坏，却只想研究聊天话术。</li><li>为了显得高级，硬去自己不懂也不喜欢的场所打卡。</li><li>朋友圈堆豪车、酒局、奢侈品，实际生活空心。</li><li>把兴趣班、社群和活动当成狩猎场，只对目标热情。</li><li>用消费替代审美，用摆拍替代真实体验。</li></ul></div><div class="ch35-box-right"><h3>成熟做法</h3><ul><li>先建立卫生、睡眠、运动、守时四个基础秩序。</li><li>选择自己愿意长期投入的兴趣，慢慢形成内容。</li><li>记录真实生活：做饭、运动、阅读、城市散步、朋友相处。</li><li>在社交场里先贡献氛围和价值，不急着索取关系。</li><li>用预算内的干净、合身、舒服，替代高消费炫耀。</li></ul></div></div></section>' +
      '<section id="兴趣半径" class="ch35-section"><div class="ch35-section-banner"><span>04</span><div><h2>四、兴趣半径：让你的生活有可分享的内容</h2><p>没有兴趣的人，聊天很容易只剩工作、游戏、抱怨和查户口。兴趣不是为了取悦女性，而是让你真的拥有可持续的生命力。</p></div></div><div class="ch35-card-grid ch35-wide-grid"><div class="ch35-card"><h3>身体型兴趣</h3><p>健身、羽毛球、游泳、徒步、骑行、攀岩。优势是改善体态和精力，也容易产生自然社交。</p><strong>入门动作：</strong><p>选一个离家近、每周能去2次的项目，坚持4周，不急着晒成果。</p></div><div class="ch35-card"><h3>审美型兴趣</h3><p>摄影、展览、电影、音乐、城市建筑、咖啡。优势是提升观察力，让约会和聊天更有画面。</p><strong>入门动作：</strong><p>每周选一个小主题：街角、光影、店铺、海报、餐具，只拍真实生活。</p></div><div class="ch35-card"><h3>手作型兴趣</h3><p>做饭、烘焙、木工、调酒、植物、整理收纳。优势是把生活变得具体，给关系带来日常温度。</p><strong>入门动作：</strong><p>先学会三道稳定菜：一道早餐、一道家常菜、一道适合朋友分享的小食。</p></div><div class="ch35-card"><h3>认知型兴趣</h3><p>阅读、播客、语言、写作、职业技能。优势是让你有观点、有表达，也能在长期关系里持续成长。</p><strong>入门动作：</strong><p>每周输出一条读书或播客笔记，只写真实收获，不装深刻。</p></div></div><div class="ch35-summary"><strong>兴趣筛选标准：</strong>你是否愿意独自做、持续做、越做越懂，并且不靠它证明自己高人一等。</div></section>' +
      '<section id="审美升级" class="ch35-section"><div class="ch35-section-banner"><span>05</span><div><h2>五、审美升级：预算内也能建立生活质感</h2><p>生活质感不等于高消费。真正有用的审美，是把有限预算花在清爽、合身、舒服、耐用和与你气质一致的地方。</p></div></div><div class="ch35-table-wrap"><table class="ch35-table"><thead><tr><th>模块</th><th>最低合格线</th><th>升级方向</th><th>避免</th></tr></thead><tbody><tr><td>发型</td><td>干净、适合脸型、定期修剪</td><td>找固定理发师，保留参考图</td><td>油头、过度造型、长期不修边</td></tr><tr><td>穿搭</td><td>合身、颜色不乱、鞋面干净</td><td>建立基础色：白、灰、蓝、黑、卡其</td><td>大logo堆砌、皱、脏、不合身</td></tr><tr><td>气味</td><td>无汗味、口气、烟味和潮味</td><td>使用淡香、干净洗衣液、车内通风</td><td>香水过浓、用香味遮掩卫生问题</td></tr><tr><td>居住</td><td>能坐、能喝水、卫生间干净</td><td>灯光、绿植、收纳、床品统一</td><td>杂物堆积、垃圾过夜、床铺混乱</td></tr><tr><td>照片</td><td>清晰、自然、不过度修图</td><td>运动、城市、做饭、朋友局各一张</td><td>怼脸自拍、炫富摆拍、低俗擦边</td></tr></tbody></table></div></section>' +
      '<section id="场景展示" class="ch35-section"><div class="ch35-section-banner"><span>06</span><div><h2>六、场景展示：从生活内容自然转化为互动空间</h2><p>展示不是炫耀，而是给别人理解你的入口。一个有生活的人，可以自然延展出聊天、邀约、共同体验和长期相处。</p></div></div><div class="ch35-scene-grid"><div class="ch35-scene-card"><span>01</span><h3>她问周末做什么</h3><p><b>弱回答：</b>在家躺着，没啥事。</p><p><b>更好：</b>上午去打球，下午把房间整理了一下，晚上准备试一道新菜。你周末偏充电还是出门？</p></div><div class="ch35-scene-card"><span>02</span><h3>她说你朋友圈挺舒服</h3><p><b>承接：</b>我现在更喜欢记录真实一点的东西，运动、吃饭、路上看到的光。不是为了显得多精彩，就是提醒自己好好生活。</p></div><div class="ch35-scene-card"><span>03</span><h3>第一次约会不知道去哪</h3><p><b>方案：</b>选低压力路线：咖啡坐一会儿，再附近散步或看一个轻展。重点是方便聊天，也方便对方早点回去。</p></div><div class="ch35-scene-card"><span>04</span><h3>朋友局里认识新人</h3><p><b>姿态：</b>先照顾全场，参与共同话题，不只围着一个女生转。你的社交口碑比单次表现更重要。</p></div><div class="ch35-scene-card"><span>05</span><h3>她到你家附近</h3><p><b>准备：</b>家里干净、有水、有纸巾、有可坐的位置。不要把到家附近默认成亲密升级，仍然给对方选择。</p></div><div class="ch35-scene-card"><span>06</span><h3>预算不高但想安排约会</h3><p><b>思路：</b>书店、展览、城市散步、市集、夜景、家常小店。便宜不等于敷衍，关键是路线顺、环境舒服、有共同体验。</p></div></div></section>' +
      '<section id="30天计划" class="ch35-section"><div class="ch35-section-banner"><span>07</span><div><h2>七、30天建设计划：从能执行的小动作开始</h2><p>不要一次性给自己设计完美生活。先用30天建立可见变化：房间更干净、身体更有劲、照片更真实、周末更有内容。</p></div></div><div class="ch35-plan-grid"><div><b>第1周 · 清场</b><span>整理房间、衣柜、洗漱台和手机相册。丢掉明显不合身衣物，完成一次理发和指甲修剪。</span></div><div><b>第2周 · 身体</b><span>固定两次运动和三次早睡。每天出门走20分钟，记录精力变化，不追求立刻变壮。</span></div><div><b>第3周 · 内容</b><span>选择一个兴趣项目体验两次：运动课、展览、做饭、摄影或城市探索。输出3张真实照片。</span></div><div><b>第4周 · 社交</b><span>参加一次朋友局或公共活动，主动贡献氛围。设计一条低成本约会路线，并复盘舒适度。</span></div></div><div class="ch35-checklist"><h3>每周复盘问题</h3><ol><li>我的房间、衣服、气味和作息是否比上周更稳定？</li><li>我有没有一个不是为了吸引别人、自己也愿意做的兴趣？</li><li>我的朋友圈是否更真实、更干净、更有生活感？</li><li>我是否把社交场当成共同体验，而不是狩猎场？</li><li>如果今天进入一段关系，我的日常是否能让对方安心？</li></ol></div></section>' +
      '<section class="ch35-section"><div class="ch35-summary ch35-final"><h2>延伸阅读</h2><p>把本章和这些章节一起看，会形成更完整的长期吸引力底盘：<a href="#/a/ch28">社交圈建设与脱单环境</a>、<a href="#/a/ch29">线上社交与相亲软件</a>、<a href="#/a/ch30">约会场景库</a>、<a href="#/a/ch34">男性沟通表达能力</a>、<a href="#/a/ch37">分手、失恋与重建</a>。</p><strong>最终原则：</strong>你不是为了让别人觉得你有生活，而是真的把日子过得更干净、更稳定、更有内容。真实变好，才是最省力的吸引力。</div></section>' +
      '</article>';
  }
'''

if 'function richCh35Html()' not in text:
    text = text.replace('\n  function richCh33Html(id) {', rich_ch35 + '\n  function richCh33Html(id) {')

text = text.replace("  function richPracticeHtml(id) {\n    if (id === 'ch38') return richCh38Html();", "  function richPracticeHtml(id) {\n    if (id === 'ch38') return richCh38Html();\n    if (id === 'ch35') return richCh35Html();")

js_path.write_text(text, encoding='utf-8')
print('updated ch35 rich html')
