from pathlib import Path

path = Path(__file__).resolve().parents[1] / 'data' / 'extra-columns.js'
text = path.read_text(encoding='utf-8')
start = text.index('  function richCh38Html() {')
end = text.index('\n  function richCh35Html() {', start)
new_func = r'''  function richCh38Html() {
    return '' +
      '<div class="ch38-mobile-nav"><a href="#核心机制">核心机制</a><a href="#直男误区">直男误区</a><a href="#主动成本">主动成本</a><a href="#接住主动">接住主动</a><a href="#推进信号">推进信号</a><a href="#实战话术">实战话术</a><a href="#训练">训练</a></div>' +
      '<article class="ch38-article">' +
      '<section class="ch38-hero"><div><span class="ch38-kicker">CH38 · 直男实战版</span><h2>反荡妇羞辱机制：让她敢主动，也愿意继续靠近</h2><p class="ch38-lead">很多直男以为“让女生主动”靠套路、刺激、拉扯。真正的核心恰好相反：你要让她确认，主动之后不会被你看轻、不会被你猴急推进、不会被你拿去吹牛、不会因为拒绝下一步而被惩罚。她一旦确认这四点，主动表达的成本就会下降，关系才会自然升温。</p><div class="ch38-hero-actions"><span>不羞辱</span><span>不猴急</span><span>不外传</span><span>能停下</span><span>会升温</span></div></div><div class="ch38-hero-card"><strong>本章一句话</strong><span>反荡妇机制不是“哄女生放下边界”，而是让她知道：她主动一点，依然会被你认真、体面、保密、尊重地对待。</span></div></section>' +
      '<div class="ch38-dashboard"><div><b>1套</b><span>主动成本降低机制</span></div><div><b>6个</b><span>直男高频翻车点</span></div><div><b>3色</b><span>推进信号判断</span></div><div><b>24句</b><span>可直接替换话术</span></div></div>' +
      '<section id="核心机制" class="ch38-section"><div class="ch38-section-banner"><span>01</span><div><h2>一、精髓：女生不是不想主动，是怕主动后被扣分</h2><p>你要看懂这件事：女性主动表达好感、邀约、亲近或性张力时，承担的社会成本通常比男性更高。她不是只在判断“喜不喜欢你”，也在判断“我主动后，你会不会变油、变急、变轻视我”。</p></div></div><div class="ch38-flow-map"><div><b>她主动</b><span>发消息、邀约、靠近、表达喜欢、聊暧昧。</span></div><div><b>她观察</b><span>你是接住，还是立刻得意、调侃、升级。</span></div><div><b>她评估</b><span>主动后是否仍被尊重，能否轻松拒绝下一步。</span></div><div><b>她决定</b><span>安全就继续释放，不安全就收回、变冷、装没事。</span></div><div><b>你胜出</b><span>稳定、保密、克制、有温度，长期比油腻话术更强。</span></div></div><div class="ch38-summary"><strong>直男必须记住：</strong>她主动不是给你“可以乱来”的许可，而是在给你一次展示成熟度的机会。你接得住，她会更愿意表达；你接不住，她下次就不主动了。</div></section>' +
      '<section id="直男误区" class="ch38-section"><div class="ch38-section-banner"><span>02</span><div><h2>二、直男最容易输的地方：一句玩笑把窗口打没</h2><p>很多机会不是没有，而是女生刚释放一点信号，男生就用低级反应把她打回防御状态。</p></div></div><div class="ch38-compare"><div class="ch38-box-wrong"><h3>翻车反应</h3><ul><li>她主动找你：你说“怎么，想我了？”让她尴尬。</li><li>她主动约你：你说“这么主动啊？”让她像做错事。</li><li>她表达喜欢：你立刻飘了，开始端架子或测试她。</li><li>她聊暧昧：你马上开黄腔，显得饥渴又不稳。</li><li>她靠近你：你默认可以继续升级，不确认舒适度。</li><li>她拒绝下一步：你冷脸、失望、阴阳怪气。</li></ul></div><div class="ch38-box-right"><h3>高手反应</h3><ul><li>先接住：谢谢她主动，让她不尴尬。</li><li>再表达：你也有兴趣，但不夸张、不油。</li><li>给台阶：她可以慢一点、改天、换方式。</li><li>守边界：不把主动等同于同意升级。</li><li>保隐私：不截图、不炫耀、不和兄弟复盘细节。</li><li>被拒绝后稳定：不惩罚，她才敢下次继续真实。</li></ul></div></div></section>' +
      '<section id="主动成本" class="ch38-section"><div class="ch38-section-banner"><span>03</span><div><h2>三、主动成本：她为什么突然变冷</h2><p>女生主动后变冷，很多时候不是她变心，而是她发现你的反应让她不安全。你要学会从成本角度看她的收回。</p></div></div><div class="ch38-card-grid"><div class="ch38-card"><h3>被轻视成本</h3><p>她怕你觉得她“很好得到”，于是降低认真程度。你越得意，她越后悔主动。</p></div><div class="ch38-card"><h3>被推进成本</h3><p>她只是表达好感，你却立刻想牵手、接吻、去私密空间，她会觉得主动等于失控。</p></div><div class="ch38-card"><h3>被传播成本</h3><p>她怕你把聊天、暧昧、亲密细节讲给朋友，主动就变成风险。</p></div><div class="ch38-card"><h3>被反咬成本</h3><p>她担心拒绝下一步时，你说“不是你先撩的吗”，于是干脆不释放信号。</p></div><div class="ch38-card"><h3>被道德审判成本</h3><p>你嘴上说开放，实际用“随便、太会、经验不少”评价她，她会立刻收回。</p></div><div class="ch38-card"><h3>被情绪惩罚成本</h3><p>她拒绝后你冷淡、消失、摆脸色，她会学到：在你面前真实表达很危险。</p></div></div></section>' +
      '<section id="接住主动" class="ch38-section"><div class="ch38-section-banner"><span>04</span><div><h2>四、接住主动三步法：感谢、回应、给空间</h2><p>直男不需要背复杂套路。女生主动时，你只做三步：先让她不尴尬，再表达你的兴趣，最后给她保留选择权。</p></div></div><div class="ch38-card-grid"><div class="ch38-card"><h3>第一步：感谢主动</h3><p>让她知道主动是被欢迎的，不是被调侃的。</p><p><b>模板：</b>“你主动说这个我挺开心的，也谢谢你愿意直接表达。”</p></div><div class="ch38-card"><h3>第二步：表达兴趣</h3><p>你不是装冷，也不是跪舔，而是清楚回应。</p><p><b>模板：</b>“我对你也有好感，所以我愿意认真接住。”</p></div><div class="ch38-card"><h3>第三步：给选择权</h3><p>让她知道可以继续，也可以慢一点。</p><p><b>模板：</b>“我们可以往前走一点，但你不舒服随时说，我们按舒服的节奏来。”</p></div><div class="ch38-card"><h3>最终公式</h3><p><b>感谢主动 + 表达兴趣 + 保护边界。</b></p><p>这套公式能同时做到升温和安全感，不会把你变成舔狗，也不会把她吓回去。</p></div></div></section>' +
      '<section id="推进信号" class="ch38-section"><div class="ch38-section-banner"><span>05</span><div><h2>五、推进信号灯：什么时候升温，什么时候停</h2><p>所谓“百战百胜”不是保证每个人都喜欢你，而是大幅减少自毁式失误：看见绿灯自然推进，看见黄灯放慢确认，看见红灯立刻停止。</p></div></div><div class="ch38-signal-grid"><div class="ch38-signal-green"><h3>绿灯：可以轻柔升温</h3><ul><li>她主动找话题、主动约时间、主动延续见面。</li><li>她靠近时放松，会回应你的靠近。</li><li>你给她选择权后，她仍然愿意继续。</li><li>她会提出自己的偏好，而不是只被动配合。</li></ul></div><div class="ch38-signal-yellow"><h3>黄灯：放慢并确认</h3><ul><li>她有兴趣，但开始犹豫、沉默、回答变短。</li><li>她说“太快了”“有点不好意思”“下次吧”。</li><li>她主动后又收回，需要你给台阶。</li><li>场景变得太晚、太私密、太难退出。</li></ul></div><div class="ch38-signal-red"><h3>红灯：马上停止</h3><ul><li>她明确说不、不要、不舒服、不方便。</li><li>她身体后撤、僵住、躲避、试图离开。</li><li>她醉酒、疲惫、情绪很差或无法清楚判断。</li><li>你想用情绪、付出、关系压力逼她改变。</li></ul></div></div><div class="ch38-summary"><strong>高手标准：</strong>能推进不稀奇，能在该停的时候停，才会让她觉得你安全、稳定、值得继续。</div></section>' +
      '<section id="场景库" class="ch38-section"><div class="ch38-section-banner"><span>06</span><div><h2>六、高频场景库：直男照着改就能少翻车</h2><p>下面不是油腻话术，而是把“接住主动但不制造压力”落到具体场景。</p></div></div><div class="ch38-scene-grid"><div class="ch38-scene-card"><span class="ch38-scene-index">01</span><h3>她主动发“在干嘛”</h3><p><b>别说：</b>“想我了？”</p><p><b>改成：</b>“刚忙完，看到你消息还挺开心。你今天怎么样？”</p></div><div class="ch38-scene-card"><span class="ch38-scene-index">02</span><h3>她主动约你</h3><p><b>别说：</b>“这么主动啊。”</p><p><b>改成：</b>“好啊，我挺开心你提出来。我们找个舒服点的地方，时间你方便为主。”</p></div><div class="ch38-scene-card"><span class="ch38-scene-index">03</span><h3>她夸你有感觉</h3><p><b>别说：</b>“那你是不是喜欢我？”</p><p><b>改成：</b>“听到你这么说我挺开心。我也觉得和你相处很舒服，可以慢慢更了解。”</p></div><div class="ch38-scene-card"><span class="ch38-scene-index">04</span><h3>她聊暧昧话题</h3><p><b>别说：</b>低俗黄腔、截图炫耀。</p><p><b>改成：</b>“这个话题可以聊，但我会注意分寸。你不想继续我们就停。”</p></div><div class="ch38-scene-card"><span class="ch38-scene-index">05</span><h3>她靠近你但有点害羞</h3><p><b>别做：</b>立刻加码升级。</p><p><b>改成：</b>“这样你舒服吗？如果有点快我们就慢一点。”</p></div><div class="ch38-scene-card"><span class="ch38-scene-index">06</span><h3>她主动后又撤回</h3><p><b>别问：</b>“你到底什么意思？”</p><p><b>改成：</b>“没关系，你不用马上确定。你刚才愿意表达我已经很开心了。”</p></div><div class="ch38-scene-card"><span class="ch38-scene-index">07</span><h3>她拒绝下一步</h3><p><b>别说：</b>“不是你先撩的吗？”</p><p><b>改成：</b>“没问题，我们停在你舒服的位置。谢谢你直接告诉我。”</p></div><div class="ch38-scene-card"><span class="ch38-scene-index">08</span><h3>朋友问你们进展</h3><p><b>别炫耀：</b>“她挺主动的。”</p><p><b>改成：</b>“我们相处还不错，具体就不拿出来说了。”</p></div></div></section>' +
      '<section id="实战话术" class="ch38-section"><div class="ch38-section-banner"><span>07</span><div><h2>七、实战话术库：把低级反应换成高胜率反应</h2><p>真正有效的话术，不是让她无法拒绝，而是让她拒绝也安全、继续也舒服。</p></div></div><div class="ch38-script-list"><div class="ch38-script-card"><h3>接主动</h3><p>“你能主动说这个我挺开心的，我会认真接住，不会拿这个调侃你。”</p><p>“我喜欢你这种直接，但你不用有压力，我们慢慢来。”</p></div><div class="ch38-script-card"><h3>轻升温</h3><p>“我对你有好感，想靠近一点，但我更在意你是不是舒服。”</p><p>“如果你也愿意，我们可以往前走一点；如果想慢一点也完全可以。”</p></div><div class="ch38-script-card"><h3>给台阶</h3><p>“刚才那个话题有点暧昧，你不好意思也正常，我们换个轻松的。”</p><p>“你不用解释太多，按你舒服的来就行。”</p></div><div class="ch38-script-card"><h3>被拒绝</h3><p>“没关系，谢谢你直接说。你放心，这不会影响我尊重你。”</p><p>“我们停一下，继续正常相处，不用尴尬。”</p></div><div class="ch38-script-card"><h3>保护隐私</h3><p>“我们的聊天和相处不会变成我跟别人炫耀的内容。”</p><p>“你愿意信任我，我也会保护这份信任。”</p></div><div class="ch38-script-card"><h3>修复失误</h3><p>“刚才那句玩笑不太合适，可能让你不舒服了，我收回。你主动表达不应该被调侃。”</p><p>“我刚才有点急了，抱歉。我们按你舒服的节奏来。”</p></div></div></section>' +
      '<section id="训练" class="ch38-section"><div class="ch38-section-banner"><span>08</span><div><h2>八、训练清单：把尊重练成本能</h2><p>直男最需要练的不是更会撩，而是主动窗口出现时不飘、不急、不嘴贱、不惩罚。</p></div></div><div class="ch38-card-grid"><div class="ch38-card"><h3>禁用词清单</h3><p>停用“随便、太会、装、经验不少、这么主动、不是你先撩的吗”。这些词会直接增加她的表达成本。</p></div><div class="ch38-card"><h3>三步回应训练</h3><p>每天写3句：感谢主动 + 表达兴趣 + 给选择权。直到你能自然说出来。</p></div><div class="ch38-card"><h3>停止训练</h3><p>模拟她说“不舒服”“太快了”“下次吧”，练习稳定回应，不解释、不冷脸、不追问。</p></div><div class="ch38-card"><h3>隐私训练</h3><p>从今天起不传播聊天截图、不复述亲密细节、不把女性主动当战绩。</p></div><div class="ch38-card"><h3>黄灯复盘</h3><p>每次她变短、变慢、变犹豫，先问：我是不是调侃、急推、压迫、让她不好拒绝？</p></div><div class="ch38-card"><h3>口碑建设</h3><p>在朋友面前也不羞辱女性主动。你的日常口碑，会决定女生是否相信你安全。</p></div></div><div class="ch38-summary"><h2>延伸阅读</h2><p>建议和这些章节一起看：<a href="#/a/ch33">亲密关系中的边界与尊重</a>、<a href="#/a/ch34">男性沟通表达能力</a>、<a href="#/a/ch19">浪漫升级与肢体接触边界</a>、<a href="#/a/ch30">约会场景库</a>、<a href="#/a/ch31">聊天素材与话题库</a>。</p><strong>最终原则：</strong>你越能让她主动后不掉价、不尴尬、不失控、不被传播，她越敢真实表达。所谓高手，不是逼别人放下边界，而是让别人靠近你时更安心。</div></section>' +
      '</article>';
  }
'''
text = text[:start] + new_func + text[end:]
path.write_text(text, encoding='utf-8')
print('replaced richCh38Html')
