from pathlib import Path

path = Path(__file__).resolve().parents[1] / 'data' / 'extra-columns.js'
text = path.read_text(encoding='utf-8')
start = text.index('  function richCh38Html() {')
end = text.index('\n  function richCh35Html() {', start)
new_func = r'''  function richCh38Html() {
    return '' +
      '<div class="ch38-mobile-nav"><a href="#核心机制">核心机制</a><a href="#直男误区">直男误区</a><a href="#主动成本">主动成本</a><a href="#四步机制">四步机制</a><a href="#推进信号">推进信号</a><a href="#场景库">场景库</a><a href="#实战话术">实战话术</a><a href="#复盘训练">复盘训练</a></div>' +
      '<article class="ch38-article">' +
      '<section class="ch38-hero"><div><span class="ch38-kicker">CH38 · 反羞辱实战专题</span><h2>反荡妇羞辱机制：让她主动后不后悔，靠近时有安全感</h2><p class="ch38-lead">这章不是教你“让女生更容易被推进”，而是教直男在女性主动、暧昧、靠近、表达欲望时，别用调侃、猴急、炫耀和冷脸把窗口打碎。真正高胜率的男人，不是每次都能推进成功，而是每次都能让对方感到：我主动不会掉价，我拒绝不会被惩罚，我靠近不会失控，我信任你不会被传播。</p><div class="ch38-hero-actions"><span>接得住</span><span>不扣分</span><span>不外传</span><span>能确认</span><span>会停下</span><span>可修复</span></div></div><div class="ch38-hero-card"><strong>最高原则</strong><span>她主动不是你加速的许可证，而是她把脆弱和信任递给你。你越稳，她越敢表达；你越急，她越要撤退。</span></div></section>' +
      '<div class="ch38-dashboard"><div><b>4步</b><span>反羞辱回应机制</span></div><div><b>8类</b><span>主动成本拆解</span></div><div><b>16个</b><span>高频实战场景</span></div><div><b>36句</b><span>可替换成熟话术</span></div></div>' +
      '<section id="核心机制" class="ch38-section"><div class="ch38-section-banner"><span>01</span><div><h2>一、精髓：反荡妇不是口号，是降低“主动成本”的机制</h2><p>女性主动的难点不只是害羞，而是主动后可能被评价、被推进、被传播、被反咬。你要做的不是让她没有防备，而是让她确认：主动表达不会让她在你这里掉分。</p></div></div><div class="ch38-flow-map"><div><b>她释放信号</b><span>找你聊天、主动邀约、表达喜欢、聊暧昧、靠近身体距离。</span></div><div><b>你先稳住</b><span>不飘、不端、不急、不黄腔，先让她知道这件事是安全的。</span></div><div><b>你正常化</b><span>告诉她主动表达很正常，不会影响你对她的尊重。</span></div><div><b>你给边界</b><span>明确不会因为她主动就默认可以升级，一切按双方舒服的节奏。</span></div><div><b>她降低防御</b><span>她不需要撤回、装冷、否认自己，因为你没有让她付出额外成本。</span></div></div><div class="ch38-summary"><strong>直男翻译：</strong>她不是在考你会不会说骚话，她是在看你有没有资格接住她的主动。你接住的是信任，不是战利品。</div></section>' +
      '<section id="直男误区" class="ch38-section"><div class="ch38-section-banner"><span>02</span><div><h2>二、直男误区翻译器：你以为在调情，她听成了羞辱</h2><p>很多男生输在一句“玩笑”。你觉得轻松，她听到的是风险；你觉得暧昧，她听到的是审判。</p></div></div><div class="ch38-compare"><div class="ch38-box-wrong"><h3>你说出口的话</h3><ul><li>“你很会啊。”</li><li>“这么主动？”</li><li>“都这样了还装？”</li><li>“你是不是撩完就跑？”</li><li>“放心，我不会说出去。”</li><li>“你以前是不是也这样？”</li><li>“你到底想不想？”</li><li>“我都对你这么好了。”</li></ul></div><div class="ch38-box-right"><h3>她可能听到的意思</h3><ul><li>你在评价我的经验和道德。</li><li>主动是可疑的、需要被调侃的。</li><li>我拒绝就是矫情，以后会被你反咬。</li><li>我不继续就会被你扣帽子。</li><li>你已经把这件事当成可传播素材。</li><li>你在盘问我的过去，而不是尊重现在。</li><li>我必须马上给答案，不然你会不高兴。</li><li>你的付出是交易，我拒绝会欠你。</li></ul></div></div><div class="ch38-summary"><strong>替代原则：</strong>不要评价她“是什么样的人”，只回应你“此刻怎么感受、接下来怎么尊重”。</div></section>' +
      '<section id="主动成本" class="ch38-section"><div class="ch38-section-banner"><span>03</span><div><h2>三、主动成本地图：她为什么释放一点又收回</h2><p>女生主动后突然变冷，常见原因不是她“作”，而是她察觉到成本上升。你越懂这些成本，越不会乱解读。</p></div></div><div class="ch38-card-grid"><div class="ch38-card"><h3>被轻视成本</h3><p>她怕你觉得她容易得到，于是降低认真程度。你的得意和端架子，都会让她后悔主动。</p></div><div class="ch38-card"><h3>被推进成本</h3><p>她只是表达好感，你却马上想肢体升级、私密空间、性暗示，她会觉得主动等于失控。</p></div><div class="ch38-card"><h3>被传播成本</h3><p>她怕聊天截图、暧昧细节、亲密进展变成你和朋友的谈资。嘴严是基本吸引力。</p></div><div class="ch38-card"><h3>被反咬成本</h3><p>她担心拒绝下一步时，你用“不是你先撩的吗”反击她，所以提前撤回信号。</p></div><div class="ch38-card"><h3>被审判成本</h3><p>“随便、太会、经验不少”这些词会把氛围从暧昧变成审判，让她立刻防御。</p></div><div class="ch38-card"><h3>被情绪惩罚成本</h3><p>她说慢一点，你冷脸、消失、阴阳怪气，她会学到：在你面前真实表达很危险。</p></div><div class="ch38-card"><h3>被误读成本</h3><p>她只是开玩笑或表达好感，你却脑补成强烈许可，下一步就开始越界。</p></div><div class="ch38-card"><h3>被绑定成本</h3><p>她主动一次，你就要求承诺、名分、答案或连续回应，她会觉得轻松感消失。</p></div></div></section>' +
      '<section id="四步机制" class="ch38-section"><div class="ch38-section-banner"><span>04</span><div><h2>四、百战少错四步机制：接住、正常化、给边界、给退路</h2><p>直男不用背复杂套路。只要把这四步练成本能，你就能在大多数暧昧窗口里显得成熟、稳定、有吸引力。</p></div></div><div class="ch38-card-grid"><div class="ch38-card"><h3>1. 接住主动</h3><p><b>目的：</b>让她不尴尬。</p><p><b>说法：</b>“你主动说这个我挺开心的，谢谢你愿意直接表达。”</p></div><div class="ch38-card"><h3>2. 正常化主动</h3><p><b>目的：</b>让她不觉得自己掉价。</p><p><b>说法：</b>“主动表达很正常，这不会让我看轻你，反而说明你真实。”</p></div><div class="ch38-card"><h3>3. 给出边界</h3><p><b>目的：</b>让她知道主动不等于默认升级。</p><p><b>说法：</b>“我也喜欢靠近你，但我们按彼此舒服的节奏来。”</p></div><div class="ch38-card"><h3>4. 给她退路</h3><p><b>目的：</b>让她可以停、慢、改主意。</p><p><b>说法：</b>“如果你觉得快，随时说，我们停一下也没关系。”</p></div></div><div class="ch38-summary"><strong>完整模板：</strong>“你这样说我挺开心的，也谢谢你信任我。你主动不会让我看轻你，我也对你有好感。我们可以慢慢靠近，但任何时候你不舒服都可以停。”</div></section>' +
      '<section id="推进信号" class="ch38-section"><div class="ch38-section-banner"><span>05</span><div><h2>五、推进信号灯：高胜率来自会判断，不是会硬冲</h2><p>所谓稳定高胜率，不是保证对方一定同意，而是让你不在黄灯时猛踩油门、不在红灯时继续施压。懂得停，才会让人愿意继续。</p></div></div><div class="ch38-signal-grid"><div class="ch38-signal-green"><h3>绿灯：可以轻柔升温</h3><ul><li>她主动延续话题、主动约时间、主动靠近。</li><li>她回应你的靠近时放松、自然、有互动。</li><li>你给她选择权后，她仍然愿意继续。</li><li>她能提出偏好，而不是只被动配合。</li><li>她拒绝某一步后，仍愿意保留其他互动。</li></ul></div><div class="ch38-signal-yellow"><h3>黄灯：放慢并确认</h3><ul><li>她开始沉默、笑得不自然、回答变短。</li><li>她说“太快了”“有点不好意思”“下次吧”。</li><li>她主动后撤回，需要你给台阶。</li><li>场景太晚、太私密、太难退出。</li><li>你自己开始着急，想用气氛推着走。</li></ul></div><div class="ch38-signal-red"><h3>红灯：马上停止</h3><ul><li>她明确说不、不要、不舒服、不方便。</li><li>她身体后撤、僵住、躲避、试图离开。</li><li>她醉酒、疲惫、情绪崩溃或判断不清。</li><li>你想用付出、礼物、关系压力逼她改变。</li><li>你发现自己接受不了她拒绝。</li></ul></div></div><div class="ch38-summary"><strong>推进口诀：</strong>绿灯小步推进，黄灯停下确认，红灯结束动作。任何亲密升级，都要允许对方轻松说“不”。</div></section>' +
      '<section id="场景库" class="ch38-section"><div class="ch38-section-banner"><span>06</span><div><h2>六、16个高频场景：从不会接，到接得稳</h2><p>下面的重点不是“背台词”，而是把反羞辱机制变成你的自然反应：不评价、不猴急、不外传、给选择。</p></div></div><div class="ch38-scene-grid"><div class="ch38-scene-card"><span class="ch38-scene-index">01</span><h3>她主动发“在干嘛”</h3><p><b>别说：</b>“想我了？”</p><p><b>改成：</b>“刚忙完，看到你消息还挺开心。你今天怎么样？”</p></div><div class="ch38-scene-card"><span class="ch38-scene-index">02</span><h3>她主动约你</h3><p><b>别说：</b>“这么主动啊。”</p><p><b>改成：</b>“好啊，我挺开心你提出来。我们找个舒服点的地方，时间你方便为主。”</p></div><div class="ch38-scene-card"><span class="ch38-scene-index">03</span><h3>她说“我是不是太主动了”</h3><p><b>别说：</b>“确实有点。”</p><p><b>改成：</b>“不会，我喜欢直接一点的表达。你不用因为主动就觉得自己掉价。”</p></div><div class="ch38-scene-card"><span class="ch38-scene-index">04</span><h3>她夸你有感觉</h3><p><b>别说：</b>“那你是不是喜欢我？”</p><p><b>改成：</b>“听到你这么说我挺开心。我也觉得和你相处很舒服，可以慢慢更了解。”</p></div><div class="ch38-scene-card"><span class="ch38-scene-index">05</span><h3>她聊暧昧话题</h3><p><b>别说：</b>低俗黄腔、截图炫耀。</p><p><b>改成：</b>“这个话题可以聊，但我会注意分寸。你不想继续我们就换轻松点的。”</p></div><div class="ch38-scene-card"><span class="ch38-scene-index">06</span><h3>她开亲密玩笑</h3><p><b>别做：</b>马上把玩笑当许可。</p><p><b>改成：</b>“你这样说有点可爱，我接收到了。但我不会乱理解，按你舒服的来。”</p></div><div class="ch38-scene-card"><span class="ch38-scene-index">07</span><h3>她主动靠近但害羞</h3><p><b>别做：</b>立刻加码升级。</p><p><b>改成：</b>“这样你舒服吗？如果有点快我们就慢一点。”</p></div><div class="ch38-scene-card"><span class="ch38-scene-index">08</span><h3>她主动后又撤回</h3><p><b>别问：</b>“你到底什么意思？”</p><p><b>改成：</b>“没关系，你不用马上确定。你刚才愿意表达我已经很开心了。”</p></div><div class="ch38-scene-card"><span class="ch38-scene-index">09</span><h3>她说“我怕你觉得我随便”</h3><p><b>别说：</b>“不会啦哈哈。”</p><p><b>改成：</b>“我不会用这种词评价你。你表达喜欢或欲望，都不影响我尊重你。”</p></div><div class="ch38-scene-card"><span class="ch38-scene-index">10</span><h3>她问“你会不会说出去”</h3><p><b>别说：</b>“放心，我不截图。”</p><p><b>改成：</b>“不会。我们的相处不是我拿去证明自己的材料，你可以放心。”</p></div><div class="ch38-scene-card"><span class="ch38-scene-index">11</span><h3>她拒绝下一步</h3><p><b>别说：</b>“不是你先撩的吗？”</p><p><b>改成：</b>“没问题，我们停在你舒服的位置。谢谢你直接告诉我。”</p></div><div class="ch38-scene-card"><span class="ch38-scene-index">12</span><h3>她说“今天不想太晚”</h3><p><b>别说：</b>“再待一会嘛。”</p><p><b>改成：</b>“好，我送你到方便的位置。今天这样也挺开心，下次再约。”</p></div><div class="ch38-scene-card"><span class="ch38-scene-index">13</span><h3>你想邀请到更私密空间</h3><p><b>别说：</b>“上去坐坐呗，别想多。”</p><p><b>改成：</b>“如果你愿意，可以上去坐会儿；如果想回去也完全没问题，我不会有情绪。”</p></div><div class="ch38-scene-card"><span class="ch38-scene-index">14</span><h3>朋友起哄问细节</h3><p><b>别炫耀：</b>“她挺主动的。”</p><p><b>改成：</b>“我们相处还不错，具体就不拿出来说了。”</p></div><div class="ch38-scene-card"><span class="ch38-scene-index">15</span><h3>你说错话让她尴尬</h3><p><b>别装没事：</b>继续开玩笑。</p><p><b>改成：</b>“刚才那句不太合适，可能让你不舒服了，我收回。你主动表达不该被调侃。”</p></div><div class="ch38-scene-card"><span class="ch38-scene-index">16</span><h3>她变冷但没明确拒绝</h3><p><b>别追问：</b>“你怎么突然这样？”</p><p><b>改成：</b>“我感觉你可能有点不自在。没关系，我们放慢一点，你不用硬接我的节奏。”</p></div></div></section>' +
      '<section id="实战话术" class="ch38-section"><div class="ch38-section-banner"><span>07</span><div><h2>七、实战话术库：让她继续舒服，而不是无法拒绝</h2><p>成熟话术的目标是降低压力、保护尊重、清楚表达兴趣。能被拒绝的话，才是安全的话。</p></div></div><div class="ch38-script-list"><div class="ch38-script-card"><h3>接主动</h3><p>“你能主动说这个我挺开心的，我会认真接住，不会拿这个调侃你。”</p><p>“我喜欢你这种直接，但你不用有压力，我们慢慢来。”</p><p>“你愿意表达，我会把它当信任，不会当笑点。”</p></div><div class="ch38-script-card"><h3>正常化</h3><p>“主动表达不丢人，也不会让你在我这里掉分。”</p><p>“喜欢、靠近、暧昧都可以真实一点，不需要装得很冷。”</p><p>“你不需要用撤回保护自己，我不会用这个评价你。”</p></div><div class="ch38-script-card"><h3>轻升温</h3><p>“我对你有好感，想靠近一点，但我更在意你是不是舒服。”</p><p>“如果你也愿意，我们可以往前走一点；如果想慢一点也完全可以。”</p><p>“我会看你的反馈，不会只按我的节奏来。”</p></div><div class="ch38-script-card"><h3>给台阶</h3><p>“刚才那个话题有点暧昧，你不好意思也正常，我们换个轻松的。”</p><p>“你不用解释太多，按你舒服的来就行。”</p><p>“你可以改变主意，这不需要向我证明什么。”</p></div><div class="ch38-script-card"><h3>被拒绝</h3><p>“没关系，谢谢你直接说。你放心，这不会影响我尊重你。”</p><p>“我们停一下，继续正常相处，不用尴尬。”</p><p>“我有点失落也会自己处理，不会让你为我的情绪负责。”</p></div><div class="ch38-script-card"><h3>保护隐私</h3><p>“我们的聊天和相处不会变成我跟别人炫耀的内容。”</p><p>“你愿意信任我，我也会保护这份信任。”</p><p>“别人问我也不会说细节，这点你可以放心。”</p></div><div class="ch38-script-card"><h3>修复失误</h3><p>“刚才那句玩笑不太合适，可能让你不舒服了，我收回。”</p><p>“我刚才有点急了，抱歉。我们按你舒服的节奏来。”</p><p>“谢谢你提醒我，我不该把你的主动当成可以随便调侃的东西。”</p></div><div class="ch38-script-card"><h3>明确兴趣但不压迫</h3><p>“我喜欢你，所以我会表达；但你不需要因为我的喜欢而勉强。”</p><p>“我想继续了解你，也尊重你慢一点的节奏。”</p><p>“你可以拒绝我，我不会用冷淡惩罚你。”</p></div></div></section>' +
      '<section class="ch38-section"><div class="ch38-section-banner"><span>08</span><div><h2>八、错误修复：已经嘴贱了，怎么补救</h2><p>真正常胜的人不是永不失误，而是发现失误后能立刻降压、道歉、修复，不让对方继续承担尴尬。</p></div></div><div class="ch38-card-grid"><div class="ch38-card"><h3>1. 立刻停止玩笑</h3><p>不要继续解释“我开玩笑的”。先停下，承认这句话可能不舒服。</p></div><div class="ch38-card"><h3>2. 明确收回评价</h3><p>“我刚才那句不该说，听起来像在评价你，我收回。”</p></div><div class="ch38-card"><h3>3. 重新给安全感</h3><p>“你主动表达不是问题，我不会因此看轻你。”</p></div><div class="ch38-card"><h3>4. 把节奏交还给她</h3><p>“我们换个轻松点的话题，或者你想停一下也可以。”</p></div></div><div class="ch38-summary"><strong>补救禁忌：</strong>不要让她反过来安慰你，不要追问“你是不是生气了”，不要用长篇解释淹没她的感受。</div></section>' +
      '<section id="复盘训练" class="ch38-section"><div class="ch38-section-banner"><span>09</span><div><h2>九、复盘训练：把尊重练成本能</h2><p>直男最该练的不是更会撩，而是在主动窗口出现时不飘、不急、不嘴贱、不惩罚。稳定执行，比花哨技巧更有用。</p></div></div><div class="ch38-card-grid"><div class="ch38-card"><h3>禁用词清单</h3><p>停用“随便、太会、装、经验不少、这么主动、都这样了、撩完就跑、不是你先撩的吗”。</p></div><div class="ch38-card"><h3>四步回应训练</h3><p>每天写3组：接住主动 + 正常化 + 给边界 + 给退路。写到你能自然说出来。</p></div><div class="ch38-card"><h3>停止训练</h3><p>模拟她说“不舒服”“太快了”“下次吧”，练习稳定回应，不解释、不冷脸、不追问。</p></div><div class="ch38-card"><h3>隐私训练</h3><p>不传播聊天截图，不复述亲密细节，不把女性主动当战绩。朋友问，也只说相处不错。</p></div><div class="ch38-card"><h3>黄灯复盘</h3><p>她变短、变慢、变犹豫时，先问：我是不是调侃、急推、压迫、让她不好拒绝？</p></div><div class="ch38-card"><h3>口碑建设</h3><p>在朋友面前也不羞辱女性主动。你的日常口碑，会决定女生是否相信你安全。</p></div><div class="ch38-card"><h3>约会前自检</h3><p>地点是否可退出？邀约是否允许拒绝？我是否预设必须升级？我能否接受她改变主意？</p></div><div class="ch38-card"><h3>约会后自检</h3><p>我是否保密？是否尊重她的节奏？是否在失落时惩罚她？是否给了下次仍可轻松见面的氛围？</p></div></div><div class="ch38-summary"><h2>延伸阅读</h2><p>建议和这些章节一起看：<a href="#/a/ch33">亲密关系中的边界与尊重</a>、<a href="#/a/ch34">男性沟通表达能力</a>、<a href="#/a/ch19">浪漫升级与肢体接触边界</a>、<a href="#/a/ch30">约会场景库</a>、<a href="#/a/ch31">聊天素材与话题库</a>。</p><strong>最终原则：</strong>真正的“百战百胜”不是让每个女生都同意你，而是你每次都不自毁：她主动后不后悔，拒绝时不害怕，靠近时不失控，离开时也觉得你体面。这才是长期吸引力。</div></section>' +
      '</article>';
  }
'''
text = text[:start] + new_func + text[end:]
path.write_text(text, encoding='utf-8')
print('upgraded richCh38Html v3')
